// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddFriendshipController from "./add_friendship_controller"
application.register("add-friendship", AddFriendshipController)

import CorrectAnswersController from "./correct_answers_controller"
application.register("correct-answers", CorrectAnswersController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HighlightAnswersController from "./highlight_answers_controller"
application.register("highlight-answers", HighlightAnswersController)

import LeaderboardController from "./leaderboard_controller"
application.register("leaderboard", LeaderboardController)

import MenubarSelectController from "./menubar_select_controller"
application.register("menubar-select", MenubarSelectController)

import ResultController from "./result_controller"
application.register("result", ResultController)
