meta_product_name: "konnec-trivia"
meta_title: "connec-trivia - General knowledge for all"
meta_description: "General knowledge for all"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@connec-trivia_twitter_account"   # required for Twitter Cards
